# =============================
#   USER-EDITABLE PARAMETERS
# =============================
task: "cluster"                            # Choices: "safety" or "cluster"
vectorizer:
  type: "word2vec"              # Choices: "bow", "tfidf", "word2vec" or "sentence_bert"
  grid_params:
    max_features: [5000, 10000]
    min_df: [1, 5]
    ngram_range:
      - [1, 1]
      - [1, 2]

classifier:
  type: "lr"                    # Choices: "lr", "nb", "svm", or "rf"
  grid_params:
    lr:
      C: [0.01, 0.1, 1]
      solver: ["liblinear", "saga"]
      max_iter: [300, 1000]
      feature_selection:
        enabled: false
        k: 1000
    nb:
      alpha: [0.1, 1]
    svm:
      C: [0.1, 1]
      kernel: ["linear"]
    rf:
      n_estimators: [100]
      max_depth: [10, 20]
      min_samples_split: [2, 5]

# =============================
#   DO NOT CHANGE BELOW
# =============================
dataset_map:
  safety: "data/processed/safety-dataset-90-5-5.hf"
  cluster: "data/processed/cluster-dataset-70-25-5.hf"
dataset_path: "${dataset_map[${task}]}"

word2vec_path: data/GoogleNews-vectors-negative300.bin
sentence_bert_model: sentence-transformers/all-MiniLM-L6-v2

results_dir: results/baselines/${task}/${classifier.type}/${vectorizer.type}
